import Link from "next/link";
import Head from "next/head";
import Header from "../components/Header";
import { sanityClient, urlFor } from "../sanity";
import { Post } from "../typings";
import Hero from "../components/Hero";
import Footer from "../components/Footer";

interface Props {
  posts: [Post];
}

export default function Home({ posts }: Props) {
  return (
    <div className="w-full bg-primary">
      <div className="max-w-screen-xl mx-auto">
        <Head>
          <title>Noor--Cyber Security Bolg</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <Hero />
        {/* <div className="flex items-center justify-between border-y border-black bg-sky-500 py-10 lg:py-0">
          <div className="px-10 space-y-5">
            <h1 className="text-5xl max-w-xl font-title">
              <Link href="https://noormohammad-profile.netlify.app/">
                <a target="_blank">
                  <span className="underline decoration-Zinc-900 decoration-4">
                    MERN-2103
                  </span>
                </a>
              </Link>{" "}
              batch from{" "}
              <span className="font-semibold">CREATIVE IT INSTITUTE</span>.
            </h1>
            <h2>
              This blog is dedicated to sum up all the important subjects we
              have been taught in class.
              <br />
              Fell free to leave a comments about the article. <br />
              If you want to add an article please procced to{" "}
              <Link href="/post/article">
                <span className="underline decoration-black font-semibold decoration-2 cursor-pointer">
                  contribute page
                </span>
              </Link>
              .
            </h2>
          </div>
          <img
            className="hidden h-32 md:inline-flex lg:h-full"
            src="https://accountabilitylab.org/wp-content/uploads/2020/03/Medium-logo.png"
            alt=""
          />
        </div> */}

        {/* Posts */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 lg:p-6">
          {posts.map((post) => (
            <Link key={post._id} href={`/post/${post.slug.current}`}>
              <div className="group cursor-pointer overflow-hidden border rounded-lg">
                <img
                  className="h-60 w-full object-cover group-hover:scale-105 transition-transform duration-200 ease-in-out"
                  src={urlFor(post.mainImage).url()}
                  alt=""
                />
                <div className="flex justify-between p-5 bg-white">
                  <div>
                    <p className="text-lg font-bold">{post.title}</p>
                    <p className="text-xs">
                      {post.description} by {post.author.name}
                    </p>
                  </div>
                  <img
                    className="h-12 w-12 rounded-full"
                    src={urlFor(post.author.image).url()}
                    alt=""
                  />
                </div>
              </div>
            </Link>
          ))}
        </div>
        <Footer />
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `*[_type == 'post']{
  _id,
  title,
  author->{
  name,
  image
},
description,
mainImage,
slug
}`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};

// export default Home;
